print("Hello, World!")
print("Welcome to Python")
print("vedant")
print("this is an python program")
name = input("Enter your name: ")
print(name +" is a good boy")
age = input("Enter your age: ")
print(age+ name)
address = input("Enter your address: ")
print(address)
Phone = input("Enter your phone number: ")
print(Phone)
branch = input("Enter your branch: ")
print(branch)
college = input("Enter your college name: ")
print(college)
detofbirth = input("Enter your date of birth: ")
print(detofbirth)
bloodgroup = input("Enter your blood group: ")
print(bloodgroup)
print(name + address + Phone + branch + college + detofbirth + bloodgroup)


name = input("Enter your name: ")
print(name +{age})
age = input("Enter your age: ")
print(age + {name})

name =input("Enter your name: ")
print("Hello, " + name)

age = input("Enter your age: ")
print("You are " + age + " years old.")

college = input("Enter your college name: ")
print("You study at " + college + ".")