print("Hello, World!")
print("Welcome to Python")
print("vedant")
print("this is an python program")
name = input("Enter your name: ")
print(name)
age = input("Enter your age: ")
print(age)
address = input("Enter your address: ")
print(address)
Phone = input("Enter your phone number: ")
print(Phone)