print("Hello, World!")
print("Welcome to Python")
print("vedant")
print("this is an python program")
name = input("Enter your name: ")
print(name)
age = input("Enter your age: ")
print(age)
address = input("Enter your address: ")
print(address)
Phone = input("Enter your phone number: ")
print(Phone)
branch = input("Enter your branch: ")
print(branch)
college = input("Enter your college name: ")
print(college)
detofbirth = input("Enter your date of birth: ")
print(detofbirth)
bloodgroup = input("Enter your blood group: ")
print(bloodgroup)